# The configuration file is designed to allow you
# to set defaults to use for a group of images.
# So, for instance an album will use the same cover image and logo,
# but different titles and output files.

# The image is built in the following order
# 1.The background
# 2. The cover image
# 3. The logo
# 4. The title text
# 5. The album text

# COLORS
# You can use the following formats for colors:
#    HTML hex code #RRGGBB
#    Common HTML named colors
#    RGB function "rgb(r,g,b)" or percentages "rgb(r%,g%,b%)"
#    HSL function "hsl(h,s,l)" or percentages "hsl(h,s%,l%)" 
#    HSV function "hsv(h,s,v)" or percentages "hsv(h,s%,v%)"

# ---------------------------------
# POSITIONS
# ---------------------------------
# You can use the following formats for positions:
# Simple : Width-Height
#    Width is one of 'left', 'center', 'right'
#    Height is one of 'top', 'center', 'bottom'
#    The title will be placed using the `gutter` parameter as a standoff
#    from the edge of the output image.
# Function :
#   The name of the function is the element that is used as a reference.
#   The following functions are available:
#     output(w, h)
#     cover(w, h)
#     border(w, h, side)
#   both 'w' and 'h' are one of 'min', 'mid', or 'max'
#   'side' is one of 'left', 'right', 'top', 'bottom'
#   The element will be placed using the `gutter` parameter as a standoff
#   from the edge of the reference.
#
#   'output(max, max)' is the equivalent of `right-bottom`


#---------------------------------
# Global Configuration
#---------------------------------

# Gap between the title or logo and the edge of the output image
gutter : 10 # --gutter

# Font - This is the font that will be used for all text items
# unless it is overridden in the configuration for that item.
# The default value will vary according to the platform.
font : 'My Cool Font' # --font

#---------------------------------
# Output Configuration
#---------------------------------
output :
  # Only PNG, JPG (or JPEG), and WEBP outputs are currently supported.
  # The extension on the filename will be used to determine the format.
  path : "/path/to/output/file.png" # --output_path

  # This is the size of the output image in WIDTHxHEIGHT format.
  size : 1980x1080 # ---output_size

  # This is the base color of the output image. It will be the
  # color of any area that isn't otherwise covered by the various elements.
  # 'black' is the default.
  color : "rgb(0,0,0)" # --output_color

#---------------------------------
# Cover Image Configuration
#---------------------------------
cover :
  # The path to the image.
  # The image can be any type supported by the `pillow` module.
  path : "/path/to/cover/file.png" # --cover_path

  # How the cover is resized to fit on the background.
  # 'square' will resize the cover, then crop to a square.
  # 'cover' will resize the cover, then crop to fit the output image.
  fit : square # --cover_fit

  # One of 'min, 'mid', or 'max'
  # Aligning depends on the orientation of the output - landscape or portrait.
  # If landscape then it is relative to the width of the output image.
  #   (min = left, mid = center, max = right)
  # If portrait then it is relative to the height of the output image.
  #   (min = top, mid = center, max = bottom)
  # This is not used if the fit is `cover`.
  align : min # --cover_align

  # One of 'min, 'mid', or 'max'
  # If the resized image needs to be cropped, this sets what area will be retained.
  # Similar to 'align', the exact effect depends on the orientation
  # of the output image.
  # 'mid' is the default
  # If the resized image is small, then this controls where in the 
  # square the image will be placed.
  # This will happen, for instance, if a portrait image is used
  # as a cover in a landscape formatted output.
  crop : mid # --cover_crop

  # border for the cover image
  # If the width is zero, then no border will be drawn. This is the default.
  border :
    color : "rgb(0,0,0)" # --cover_border_color
    width : 0 # --cover_border_width

#---------------------------------
# Logo Image Configuration
#---------------------------------
logo :
  # The path to the logo image
  # The image can be any type supported by the `pillow` module.
  path : "/path/to/image/file.jpg" # --logo

  # size in pixels for the logo. aspect ratio will be preserved.
  # The largest dimension of the logo will be scaled to this size.
  size : 200 # size in pixels --logo_size

  # Algorithm to compute a mask for the logo image.
  # "self" - uses the luminance channel of the image as-is. This means that
  #     the background will show through at least a little on any part of
  #     the logo image that is not fully white.
  # "black" - clamps the luminance channel, so that only black pixels in the logo 
  #     are transparent.
  # "alpha" - uses the alpha channel of the image as a mask.
  # "auto" - automatically chooses between "alpha" and "black". This is the default.
  # "none" : No masking is done.
  mask : auto # --logo_mask

  # Position for the logo on the output.
  # See above for details
  # right-bottom is the default
  position : right-bottom # --logo_position

#---------------------------------
# Track Title Configuration
#---------------------------------
title :
  text : "This is the title" # --title

  # Size of the text in pixels (not points)
  # This size is a maximum. If the text does not fit, it will be scaled down.
  size : 200 # --title_size

  # Font to use for the title.
  # defaults to the global font setting if not given (see above).
  font : 'DejaVuSans.ttf' # --title_font

  # Position for the title on the output.
  # See above for details
  # right-top is the default
  position : right-top # --title_position

  # Fill color for the title
  # see above for color formats.
  # White is the default
  fill : "hsv(0,0%,100%)" # --title_fill

  # Control the stroke.
  # See above for color formats.
  # If width is 0, no stroke is drawn (the default).
  # Default stroke color is white.
  stroke :
    color : "hsv(0,0%,100%)" # --title_stroke_color
    width : 2 # --title_stroke_width

#---------------------------------
# Album Title Configuration
#---------------------------------
album :
  text : "This is the album name" # --album

  # Size of the text in pixels (not points)
  # This size is a maximum. If the text does not fit, it will be scaled down.
  size : 200 # --size_size

  # Font to use for the text.
  # defaults to the global font setting if not given (see above).
  font : 'DejaVuSans.ttf' # --album_font

  # Position for the text on the output.
  # See above for details
  # right-center is the default
  position : right-center # --album_position

  # Fill color for the text
  # see above for color formats.
  # White is the default
  fill : "hsv(0,0%,100%)" # --album_fill

  # Control the stroke.
  # See above for color formats.
  # If width is 0, no stroke is drawn (the default).
  # Default stroke color is white.
  stroke :
    color : "hsv(0,0%,100%)" # --album_stroke_color
    width : 2 # --album_stroke_width

