mupic_config_file : include_stmt? setting_stmt* default_stmt* _stmts

_stmts : statement*

?statement : output_stmt
    | image_stmt  | text_stmt
    | template_stmt | render_stmt

// ---- INCLUDE ----------------------------------------------
include_stmt : "include" STRING_VALUE

// ---- SET ----------------------------------------------
setting_stmt : "set" "zorder" WORD -> zorder_stmt

// ---- DEFAULT ----------------------------------------------
default_stmt : "default" WORD STRING_VALUE

// ---- OUTPUT ----------------------------------------------
output_stmt : "output" "{" output_setting+ "}"
OUTPUT_FIT : "cover" | "contain"
?output_setting : path_option
    | size_2d_option
    | color_option
    | "background" "=" STRING_VALUE -> background_option
    | "fit" "=" OUTPUT_FIT -> fit_option
    | margin_int_option
    | border_spec

// ---- IMAGE ----------------------------------------------
image_stmt : "image" [(ESCAPED_STRING | CNAME) [SIGNED_NUMBER]] "{" image_setting+ "}"
?image_setting :
    | "size" "=" /max(square)?/ -> size_max
    | "size" "=" "scale" "," SIGNED_NUMBER -> scale_size
    | "size" "=" SIZE -> size_2d_option
    | "transform" "=" "scale" "," SIGNED_NUMBER "," SIGNED_NUMBER -> transform_scale
    | "rotation" "=" SIGNED_NUMBER -> rotation_int_option
    | position_option
    | border_spec
    | content_spec
    | "color" "=" (HEXCOLOR | FUNCCOLOR | ESCAPED_STRING | CNAME) -> color_option
    | border_spec
    | margin_int_option

content_spec.20 : "content" "{" content_settings+ "}"
?content_settings : "file" "=" STRING_VALUE -> file_option
    | "color" "=" (HEXCOLOR | FUNCCOLOR | ESCAPED_STRING | CNAME) -> color_option
    | "mask" "=" WORD -> mask_option
    | fit_option
    
fit_option : "fit" "=" WORD ["," WORD]

// ---- TEXT ----------------------------------------------
text_stmt : "text" [(ESCAPED_STRING | CNAME) [ INTEGER]] "{" text_setting+ "}"
?text_setting : "text" "=" ESCAPED_STRING -> text_option
    | "size" "=" INTEGER -> size_int_option
    | position_option
    | color_option
    | "rotation" "=" INTEGER -> rotation_int_option
    | "fill" "=" STRING_VALUE -> fill_option // This is a color
    | "font" "=" STRING_VALUE -> font_option
    | stroke_spec
    | "gap" "=" INTEGER -> gap_int_option
    | border_spec

// ---- TEMPLATE ----------------------------------------------
template_stmt : "template" CNAME "(" parm_list ")" TBODY
parm_list : /[a-zA-Z]/ ("," /[a-zA-Z]/)*
TBODY.50 : /\{\{\{/ /.+?(?=}}})/s /\}\}\}/

// ---- RENDER ----------------------------------------------
render_stmt : "render" CNAME "(" render_list ")"
render_list : STRING_VALUE ("," STRING_VALUE)*

// ---- Common symbols ----------------------------------------

border_spec : "border" "{" border_setting+ "}"
    | "border" "=" (HEXCOLOR | FUNCCOLOR | ESCAPED_STRING | CNAME) ","  INTEGER-> simple_border
// Changing this to directly use color_option rule
// causes a reduce/reduce conflict with stroke_setting
?border_setting : "color" "=" (HEXCOLOR | FUNCCOLOR | ESCAPED_STRING | CNAME) -> color_option
    | width_spec
    | "round" "=" INTEGER -> round_int_option

stroke_spec : "stroke" "{" stroke_setting+ "}"
?stroke_setting : color_option
    | "width" "=" INTEGER -> width_int_option

width_spec : "width" "=" INTEGER
    | "width" "{" INTEGER "}"
    | "width" "{" one_side+ "}"
one_side : /[ltrb]/ "=" INTEGER

path_option : "path" "=" STRING_VALUE
margin_int_option : "margin" "=" INTEGER
size_2d_option : "size" "=" SIZE
position_option : "position" "=" STRING_VALUE
color_option : "color" "=" (HEXCOLOR | FUNCCOLOR | ESCAPED_STRING | CNAME)

SIZE : /\d+(x\d+)?/
INTEGER : /[-+]?\d+/
BARE_STRING : /[^)( \t,\n"']+/

// Priority is to make it tried before SH_COMMENT
HEXCOLOR.10 : /\#[a-fA-F0-9]+/
FUNCCOLOR.30 : /(rgb|hsv|hsl) \( [^(]+ \)/ix
//RGBCOLOR.30 : /rgb\( *\d+ *, *\d+ *, *\d+ *\)/i
//HSVCOLOR.30 : /hsv\( *\d+ *, *\d+\% *, *\d+% *\)/i
//HSLCOLOR.30 : /hsl\( *\d+ *, *\d+\% *, *\d+% *\)/i


%import common.ESCAPED_STRING
%import common.WORD
%import common.CNAME
%import common.SIGNED_NUMBER

STRING_VALUE : ESCAPED_STRING | BARE_STRING
MINMAX.10 : /min\b|mid\b|max\b/i



%import common.SH_COMMENT
%import common.WS
%ignore SH_COMMENT
%ignore WS
